# icon:folder-open[] HTTP Whiteboard - OSGI Compendium 6.0
Raymond Augé <raymond.auge@liferay.com>
:icons: font
:title: How webapps should have been!
:description: Presentation at Eclipsecon Europe 2014
:hashtags: #OSGi #eclipsecon #httpwhiteboard
:twitter: @rotty3000

[big]**How webapps should have been!**

|===
|**{author}**
|**icon:twitter[] {twitter} \| {hashtags}**
|===

<<<

== icon:th-list[] Outline

[cols="2*", frame="none"]
|===
|
icon:arrow-circle-right[] [big]**State of the Art** +
icon:arrow-circle-right[] [big]**Http Whiteboard** +
icon:arrow-circle-right[] [big]**Design Goals** +
//icon:arrow-circle-right[] [big]**From Monoliths to ... Anything, Please!** +
icon:arrow-circle-right[] [big]**ServletContextHelper** +
icon:arrow-circle-right[] [big]**Servlets** +
icon:arrow-circle-right[] [big]**Resources** +
|
icon:arrow-circle-right[] [big]**Filters** +
icon:arrow-circle-right[] [big]**Event Listeners** +
icon:arrow-circle-right[] [big]**Error Pages** +
icon:arrow-circle-right[] [big]**DTOs** +
icon:arrow-circle-right[] [big]**In Action** +
icon:arrow-circle-right[] [big]**Verdict** +
|===

<<<

== icon:arrow-circle-right[] State of the Art

* Current Java webapps are generally uninspiring
* There is little to no definition of modularity in Java webapps
* Webapps easily become monoliths
* A weak webapp lifecycle of has been badly abused
* Cross platform support is incredibly complex due to what remains unspecified

<<<

== icon:arrow-circle-right[] Http Whiteboard

* Started as *RFC 189 - Http Service Updates*
* Evolved into *OSGi Enterprise Section 140 - Http Whiteboard Specification*
** .. an addition which left the original *Http Service* untouched
* Added whiteboard style programming model

<<<

== icon:arrow-circle-right[] Design Goals

* Bring support for Servlet 3.0 (minimally)
* Enhancements which were long missing
** multiple url patterns
** servlet filters
** event listeners
** error pages
* Clarify relationship between contexts in OSGi and Servlet spec
* Introspection of current state of http services
* Define a capability namespace

////
<<<

== icon:arrow-circle-right[] From Monoliths to ... Anything, Please!

* Every modern software engineering discussion spews buckets of descriptive buzzwords all describing in every way anything that is [big]*!= _monolith_*

See http://www.reactivemanifesto.org/[The Reactive Manifesto] for details.
////

<<<

== icon:arrow-circle-right[] ServletContextHelper

[source,java]
.SampleServletContextHelper.java
----
@Component(
	property = {
		HttpWhiteboardConstants.HTTP_WHITEBOARD_CONTEXT_NAME + "=default",
		HttpWhiteboardConstants.HTTP_WHITEBOARD_CONTEXT_PATH + "=/"
	}
)
public class SampleServletContextHelper extends ServletContextHelper {
}
----

<<<

== icon:arrow-circle-right[] Servlets

[source,java]
.SampleServlet.java
----
@Component(
	property = {
		HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_PATTERN + "=/"
	},
	service = Servlet.class
)
public class SampleServlet extends HttpServlet {
	@Override
	protected void service(
			HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException {

		PrintWriter writer = response.getWriter();

		writer.write("Hello World!");
	}
}
----

<<<

== icon:arrow-circle-right[] Resources

[source,java]
.SampleResources.java
----
@Component(
	property = {
		HttpWhiteboardConstants.HTTP_WHITEBOARD_RESOURCE_PREFIX + "=/META-INF/resources",
		HttpWhiteboardConstants.HTTP_WHITEBOARD_RESOURCE_PATTERN + "=/resources/*"
	}
)
public class SampleResources {
}
----

<<<

== icon:arrow-circle-right[] Filters

[source,java]
.SampleFilter.java
----
@Component(
	property = {
		HttpWhiteboardConstants.HTTP_WHITEBOARD_FILTER_PATTERN + "=/*"
	}
)
public class SampleFilter implements Filter {
	@Override
	public void doFilter(
			ServletRequest request, ServletResponse response,
			FilterChain filterChain)
		throws IOException, ServletException {

		filterChain.doFilter(request, response);
	}
}
----

<<<

== icon:arrow-circle-right[] Event Listeners

[source,java]
.SampleServletContextListener.java
----
@Component
public class SampleServletContextListener implements ServletContextListener {

	@Override
	public void contextDestroyed(ServletContextEvent arg0) {
	}

	@Override
	public void contextInitialized(ServletContextEvent arg0) {
	}

}
----

<<<

== icon:arrow-circle-right[] Error Pages

[source,java]
.SampleErrorPage.java
----
@Component(
	property={
		HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_ERROR_PAGE + "=java.io.IOException",
		HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_ERROR_PAGE + "=5xx"
	},
	service = Servlet.class
)
public class SampleErrorPage extends HttpServlet {

	@Override
	protected void service(
			HttpServletRequest request, HttpServletResponse response)
		throws IOException, ServletException {

		//
	}

}
----

<<<

== icon:arrow-circle-right[] DTOs

[source,java]
.SampleDTOReportServlet.java
----
@Component(
	immediate  = true,
	property = {
		HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_PATTERN + "=/dto"
	},
	service = Servlet.class
)
public class SampleDTOReportServlet extends HttpServlet {

	@Override
	protected void service(
			HttpServletRequest request, HttpServletResponse response)
		throws IOException, ServletException {

		final HttpServiceRuntime httpServiceRuntime = _httpServiceRuntime;

		if (httpServiceRuntime == null) {
			response.sendError(
				HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
				"Something went terribly wrong...");

			return;
		}

		response.setContentType("application/json");
		response.setCharacterEncoding("UTF-8");

		PrintWriter writer = response.getWriter();

		writer.write(httpServiceRuntime.getRuntimeDTO().toString());

		writer.close();
	}

	@Reference(unbind = "-")
	protected void setHttpServiceRuntime(
		HttpServiceRuntime httpServiceRuntime) {

		_httpServiceRuntime = httpServiceRuntime;
	}

	private volatile HttpServiceRuntime _httpServiceRuntime;

}
----

<<<

== icon:arrow-circle-right[] In Action

* [big]**DEMO TIME!**

<<<

== icon:arrow-circle-right[] Verdict

* I'm excited with the result of the Http Whiteboard specification
* http://www.osgi.org/Specifications/Drafts[OSGi R6 Early Draft]
* https://www.eclipse.org/eclipse/news/4.5/M3/[Eclipse Project 4.5 M3 - New and Noteworthy] - **Friday**
* There's very little time left to get your feedback in. But, if you have any, please contact myself or any member of the EEG

[big]**Thank you!**