# icon:folder-open[] Case Study
Raymond Augé <raymond.auge@liferay.com>
:icons: font
:title: Case Study - Semantic Versioning A Large Existing Codebase
:description: Presentation at EclipseCon 2014
:hashtags: #eclipsecon #semver
:twitter: @rotty3000

[.subtitle]
**Semantic Versioning A Large Existing Codebase**

**{author}** +
EclipseCon 2014

**{twitter} | {hashtags}**

<<<

== icon:user[] The main character

The project in question, **Liferay Portal**, is a very large, single repository,
open source application. The project is maintained by a small (sub 500 employee)
company **Liferay, Inc.**

* portal software
* product company
* un-funded
* more than a thousand clients

<<<

== icon:gears[] The situation

* organic growth
* large number of developers
** wide range of skill levels
* years of effort
* millions of lines of code
* single software repository
* _effectively_ single artifact
* thousands of features

<<<

== icon:warning-sign[] The problem(s)

* breaking API
* binary patching
* monolithic upgrades
* no feature updates

<<<

== icon:puzzle-piece[] The solution

Rather a very significant part of the solution is Semantic Versioning.

* OSGi Alliance Semantic Versioning whitepaper
** http://www.osgi.org/wiki/uploads/Links/SemanticVersioning.pdf
* lots of work, who's going to do it?

<<<

== icon:wrench[] The available tools

The key to semantic versioning is in the tooling.

* human versioning is biased, error prone and boring but essential
* let machines do most of the work

* BND
** http://www.aqute.biz/Bnd/Bnd
** http://bndtools.org/
* http://www.aqute.biz/Bnd/Versioning
* built tool support
* show a pure example of baseline feature

```
java -jar biz.aQute.bnd-latest.jar baseline -d ./biz.aQute.bnd-latest.jar /other/bnd.jar
```

```
===============================================================
  biz.aQute.bnd 2.3.0.20140315-151701-2.2.0.20131017-210830
===============================================================
  Package                                            Delta      New        Old        Suggest    If Prov.
  aQute.bnd.build                                    MINOR      2.3.0      2.2.0      ok         -
  aQute.bnd.header                                   MINOR      1.3.0      1.2.0      ok         -
  aQute.bnd.osgi                                     MINOR      2.2.0      2.1.3      ok         -
  aQute.bnd.service.classparser                      ADDED      1.0.0      -          ok         -
  aQute.bnd.service.extension                        ADDED      1.0.0      -          ok         -
  aQute.bnd.service.phases                           ADDED      1.0.0      -          ok         -
  aQute.bnd.service.repository                       MINOR      1.3.0      1.1.0      ok         -
  aQute.bnd.service.url                              MINOR      1.2.0      1.1.0      ok         -
  aQute.bnd.version                                  MINOR      1.1.0      1.0.0      ok         -
```

<<<

== icon:crop[] The adaptations

Is this enough information for the least experienced developers to understand
how things get broken?

* make it work for us
** the BND library does and intense analysis including exceptionally detailed
analytics about APIs.
* show the integration / report
* even basic BND is useful

<<<

== icon:exclamation[] The conclusion

* do we have semantic versioning
* has helped
* what does the future look like

<<<

== icon:power-off[] Thank You!

[.topic.ending]
=== Questions?

////
[source,java]
.Test.java
----
if (true) {
	System.out.println("Hello World!")  <1>
}
----

<1> This line should do something cool!
////

[#footer]
**@rotty3000 | #eclisecon #semver**