DROP TABLE IF EXISTS USERS_;
CREATE TABLE USERS_(EMAIL VARCHAR(255) PRIMARY KEY,FNAME VARCHAR(255),LNAME VARCHAR(255),PASSWORD VARCHAR(255),SECRET_KEY  VARCHAR(255), COUNTER BIGINT);  

AS SELECT * FROM CSVREAD('/Users/kameshs/Projects/auth.otp/test_data.csv');